# Generated by Django 6.1 on 2026-08-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionfield',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='section',
            name='layout_style',
            field=models.CharField(choices=[('TABLE', 'Table View'), ('GRID', 'Grid/Card View')], default='TABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='section',
            name='on_submit_action',
            field=models.CharField(choices=[('NONE', 'Do Nothing'), ('EMAIL_MANAGER', 'Email Manager')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='sectionfield',
            name='options',
            field=models.TextField(blank=True, help_text='Comma separated options for choice fields', null=True),
        ),
        migrations.AddField(
            model_name='sectionfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sectionfield',
            name='field_type',
            field=models.CharField(choices=[('HEADING', 'Heading / Title'), ('DESCRIPTION', 'Description / Text Block'), ('TEXT', 'Short Text'), ('TEXTAREA', 'Long Text (Paragraph)'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('FILE', 'Image/File'), ('DROPDOWN', 'Dropdown Select'), ('RADIO', 'Radio Buttons (Single Choice)'), ('CHECKBOX', 'Checkboxes (Multiple Choice)')], default='TEXT', max_length=20),
        ),
    ]
