# Generated by Django 6.1 on 2026-08-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_sectionfield_options_section_layout_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='show_in_sidebar',
            field=models.BooleanField(default=False),
        ),
    ]
