# Generated by Django 6.1 on 2026-08-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_section_show_in_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='sectionfield',
            name='field_type',
            field=models.CharField(choices=[('HEADING', 'Heading / Title'), ('DESCRIPTION', 'Description / Text Block'), ('TEXT', 'Short Text'), ('TEXTAREA', 'Long Text (Paragraph)'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('FILE', 'Image/File'), ('DROPDOWN', 'Dropdown Select'), ('RADIO', 'Radio Buttons (Single Choice)'), ('CHECKBOX', 'Checkboxes (Multiple Choice)'), ('EMPLOYEE_SELECT', 'Employee Link (Select User)')], default='TEXT', max_length=20),
        ),
    ]
