# Generated by Django 6.1 on 2026-08-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_user_profile_picture_alter_sectionfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='layout_style',
            field=models.CharField(choices=[('TABLE', 'Standard Table (Rows & Columns)'), ('GRID', 'Grid Cards (Modern blocks)'), ('LIST', 'List View (Stacked borders)'), ('MASONRY', 'Masonry (Pinterest-style)'), ('MINIMAL', 'Minimalist (Clean text-only)')], default='TABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionfield',
            name='field_type',
            field=models.CharField(choices=[('HEADING', 'Heading / Title'), ('DESCRIPTION', 'Description / Text Block'), ('TEXT', 'Short Text'), ('TEXTAREA', 'Long Text (Paragraph)'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('FILE', 'Image/File'), ('DROPDOWN', 'Dropdown Select'), ('RADIO', 'Radio Buttons (Single Choice)'), ('CHECKBOX', 'Checkboxes (Multiple Choice)')], default='TEXT', max_length=20),
        ),
    ]
