# Generated by Django 6.1 on 2026-08-07 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_section_layout_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='P&M Department', max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='system/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='portal.companypost'),
        ),
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('DEO', 'DEO (Data Entry Operator)'), ('PENDING', 'Pending Approval')], default='PENDING', max_length=20),
        ),
    ]
