# Generated by Django 6.1 on 2026-08-07 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_systemsettings_alter_user_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='verify_posts',
            field=models.ManyToManyField(blank=True, related_name='verifiable_sections', to='portal.companypost'),
        ),
        migrations.AddField(
            model_name='sectionentry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified/Approved'), ('REJECTED', 'Rejected/Issue Found')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='sectionentry',
            name='verification_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sectionentry',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sectionentry',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
