# Generated by Django 6.1 on 2026-08-07 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_section_verify_posts_sectionentry_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='verify_posts',
        ),
        migrations.AddField(
            model_name='section',
            name='verify_users',
            field=models.ManyToManyField(blank=True, related_name='verifiable_sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
