# Generated by Django 6.1 on 2026-08-07 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_section_verify_posts_section_verify_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='edit_posts',
        ),
        migrations.RemoveField(
            model_name='section',
            name='view_posts',
        ),
        migrations.AddField(
            model_name='section',
            name='edit_users',
            field=models.ManyToManyField(blank=True, related_name='editable_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='view_users',
            field=models.ManyToManyField(blank=True, related_name='viewable_sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
