# Generated by Django 6.1 on 2026-08-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_section_edit_posts_remove_section_view_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
