# Generated by Django 6.1 on 2026-08-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_section_is_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
