# Generated by Django 6.1 on 2026-08-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_section_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='trash_retention_days',
            field=models.IntegerField(default=30, help_text='Number of days before archived modules are permanently deleted'),
        ),
    ]
