# Generated by Django 6.1 on 2026-08-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_systemsettings_trash_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionfield',
            name='is_filterable',
            field=models.BooleanField(default=False, help_text='If true, a dropdown filter will appear for this field in data view'),
        ),
    ]
