# Generated by Django 6.1 on 2026-08-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_sectionfield_is_filterable'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='enable_date_filter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='enable_date_range_filter',
            field=models.BooleanField(default=False),
        ),
    ]
