# Generated by Django 6.1 on 2026-08-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_section_enable_date_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='enable_dropdown_filter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='enable_search_filter',
            field=models.BooleanField(default=True),
        ),
    ]
