# Generated by Django 6.1 on 2026-08-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_section_enable_dropdown_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='require_approval',
            field=models.BooleanField(default=True),
        ),
    ]
