# Generated by Django 6.1 on 2026-08-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_section_require_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionfield',
            name='field_type',
            field=models.CharField(choices=[('HEADING', 'Heading / Title'), ('DESCRIPTION', 'Description / Text Block'), ('TEXT', 'Short Text'), ('TEXTAREA', 'Long Text (Paragraph)'), ('NUMBER', 'Number'), ('DATE', 'Date'), ('TIME', 'Time (Hour & Minute)'), ('FILE', 'Image/File'), ('DROPDOWN', 'Dropdown Select'), ('RADIO', 'Radio Buttons (Single Choice)'), ('CHECKBOX', 'Checkboxes (Multiple Choice)')], default='TEXT', max_length=20),
        ),
    ]
