# Generated by Django 6.1 on 2026-08-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_alter_sectionfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='show_pending_stat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='show_rejected_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='show_total_stat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='show_verified_stat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sectionfield',
            name='show_sum_on_dashboard',
            field=models.BooleanField(default=True),
        ),
    ]
