# Generated by Django 6.1 on 2026-08-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_section_show_pending_stat_section_show_rejected_stat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='show_pending_stat',
        ),
        migrations.RemoveField(
            model_name='section',
            name='show_rejected_stat',
        ),
        migrations.RemoveField(
            model_name='section',
            name='show_total_stat',
        ),
        migrations.RemoveField(
            model_name='section',
            name='show_verified_stat',
        ),
        migrations.RemoveField(
            model_name='sectionfield',
            name='show_sum_on_dashboard',
        ),
        migrations.AddField(
            model_name='sectionfield',
            name='show_on_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
