# Generated by Django 5.2.15 on 2026-08-14 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_remove_section_show_pending_stat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionfield',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='This field will only show if the selected parent field has a specific value.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_fields', to='portal.sectionfield'),
        ),
        migrations.AddField(
            model_name='sectionfield',
            name='depends_on_value',
            field=models.CharField(blank=True, help_text='The value the parent field must have for this field to appear.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companypost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sectionfield',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
