# Generated by Django 5.2.15 on 2026-08-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_sectionfield_depends_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='module_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Form (Custom Fields)'), ('FLEET', 'Fleet / Machinery (Rigsar Vajra)')], default='STANDARD', max_length=20),
        ),
    ]
