# Generated by Django 5.2.15 on 2026-08-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_section_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='fleet_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
