# Generated by Django 5.2.15 on 2026-08-20 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_section_fleet_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('WORK_VISA', 'Work Visa / Residence Permit'), ('INDIAN_LICENSE', 'Indian HMV License'), ('FOREIGN_LICENSE', 'Foreign Host Country License'), ('IDP', 'International Driving Permit (IDP)'), ('MEDICAL', 'Medical Fitness Certificate'), ('CONTRACT', 'Employment Contract'), ('PCC', 'Police Clearance Certificate'), ('HAZMAT', 'Hazmat/Special Certification'), ('OTHER', 'Other License/Permit')], max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issuing_country', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='employee_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
