# Generated by Django 5.2.15 on 2026-08-20 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_employeedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, unique=True, verbose_name='Employee Registration')),
                ('name', models.CharField(max_length=150)),
                ('nationality', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('work_permit_no', models.CharField(blank=True, max_length=100, null=True)),
                ('work_permit_expiry', models.DateField(blank=True, null=True)),
                ('passport_details', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Terminated', 'Terminated')], default='Active', max_length=50)),
                ('contractor_agency', models.CharField(blank=True, max_length=150, null=True, verbose_name='Contractor / Hiring Agency')),
                ('document_upload', models.FileField(blank=True, null=True, upload_to='employees/docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.employee'),
        ),
    ]
