# Generated by Django 5.2.15 on 2026-08-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_employee_alter_employeedocument_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee Registration'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
