# Generated by Django 5.2.15 on 2026-08-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_vehicledocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_operator', models.CharField(blank=True, max_length=150, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('reports_to', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=150, null=True)),
                ('policy_no', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
