# Generated by Django 5.2.15 on 2026-08-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_insurancedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='document_type',
            field=models.CharField(blank=True, default='General Document', max_length=100, null=True),
        ),
    ]
