# Generated by Django 6.1 on 2026-08-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_driver_section_remove_fleetvehicle_section_and_more'),
        ('portal', '0028_employee_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionentry',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectionfield',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectionentry',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='sectionentry',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='sectionfield',
            name='depends_on',
        ),
        migrations.AlterField(
            model_name='companypost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='insurancedocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SectionEntry',
        ),
        migrations.DeleteModel(
            name='SectionField',
        ),
    ]
