# Generated by Django 6.1 on 2026-08-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_user_notification_prefs_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('machinery', models.CharField(max_length=100)),
                ('zone_1_2_day', models.IntegerField(default=0)),
                ('zone_1_2_night', models.IntegerField(default=0)),
                ('zone_3_4_day', models.IntegerField(default=0)),
                ('zone_3_4_night', models.IntegerField(default=0)),
                ('borrow_area_day', models.IntegerField(default=0)),
                ('borrow_area_night', models.IntegerField(default=0)),
                ('culvert_area_day', models.IntegerField(default=0)),
                ('culvert_area_night', models.IntegerField(default=0)),
                ('batching_plant_day', models.IntegerField(default=0)),
                ('batching_plant_night', models.IntegerField(default=0)),
                ('crushing_plant_day', models.IntegerField(default=0)),
                ('crushing_plant_night', models.IntegerField(default=0)),
                ('road_maint_day', models.IntegerField(default=0)),
                ('road_maint_night', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
