# Generated by Django 6.1 on 2026-08-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_dailydeployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='current_shift',
            field=models.CharField(blank=True, choices=[('Day', 'Day Shift'), ('Night', 'Night Shift'), ('Reliever', 'Reliever / Other')], default='Day', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='shift_remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
