# Generated by Django 6.1 on 2026-08-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_employee_current_shift_employee_shift_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_shift',
            field=models.CharField(blank=True, choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], default='Day', max_length=50, null=True),
        ),
    ]
