# Generated by Django 6.1 on 2026-08-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_alter_employee_current_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
