# Generated by Django 6.1 on 2026-08-24 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_user_assigned_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydeployment',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments_entered', to=settings.AUTH_USER_MODEL),
        ),
    ]
