# Generated by Django 6.1 on 2026-08-26 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0037_message_file_message_file_type_message_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='portal.vehicle'),
        ),
    ]
