# Generated by Django 6.1 on 2026-08-26 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_vehiclemovement'),
        ('portal', '0038_employee_assigned_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='fleet.fleetvehicle'),
        ),
    ]
