# Generated by Django 6.1 on 2026-08-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_alter_employee_assigned_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last activity heartbeat (for chat presence)', null=True),
        ),
    ]
