# Generated by Django 6.1 on 2026-08-31 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_working_shift_hours',
            field=models.IntegerField(default=12, help_text='Default working hours for shift rosters'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='doc_expiry_threshold',
            field=models.IntegerField(default=90, help_text='Default warning threshold (in days) for document expiries'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_email_notifications',
            field=models.BooleanField(default=False, help_text='Enable global email alerts for critical events'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_low_stock_alerts',
            field=models.BooleanField(default=True, help_text='Enable alerts for spare parts that fall below reorder level'),
        ),
    ]
