# Generated by Django 6.1 on 2026-09-01 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_add_soft_delete_fields'),
        ('portal', '0041_systemsettings_default_working_shift_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVehicleAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('shift', models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], db_index=True, default='Day', max_length=10)),
                ('category', models.CharField(choices=[('Scania', 'Scania / Dumper (10W/12W)'), ('Excavator', 'Excavator'), ('Grader', 'Motor Grader'), ('Compactor', 'Compactor / Roller'), ('Other', 'Other Machinery')], db_index=True, max_length=50)),
                ('vehicle_regn', models.CharField(db_index=True, help_text='Registration No snapshot', max_length=100)),
                ('driver_name', models.CharField(help_text='Driver / Operator Name', max_length=150)),
                ('driver_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('location_zone', models.CharField(choices=[('Zone 1 & 2', 'Zone 1 & 2'), ('Zone 3 & 4', 'Zone 3 & 4'), ('Borrow Area', 'Borrow Area'), ('Culvert Area', 'Culvert Area'), ('Batching Plant', 'Batching Plant'), ('Crushing Plant', 'Crushing Plant'), ('Road Maintenance', 'Road Maintenance'), ('Other Location', 'Other Location')], default='Zone 1 & 2', max_length=100)),
                ('work_order_no', models.CharField(blank=True, max_length=150, null=True)),
                ('vendor', models.CharField(blank=True, max_length=200, null=True)),
                ('start_hmr', models.FloatField(blank=True, help_text='Starting HMR/KMR', null=True)),
                ('end_hmr', models.FloatField(blank=True, help_text='Ending HMR/KMR', null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='portal.employee')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_allocations_entered', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_allocations', to='fleet.fleetvehicle')),
            ],
            options={
                'ordering': ['-date', 'category', 'vehicle_regn'],
            },
        ),
    ]
