# Generated by Django 6.1 on 2026-09-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0042_dailyvehicleallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyvehicleallocation',
            name='driver_emp_id',
            field=models.CharField(blank=True, help_text='Driver Employee ID', max_length=50, null=True),
        ),
    ]
