# Generated by Django 6.1 on 2026-09-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0043_dailyvehicleallocation_driver_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='captain_category',
            field=models.CharField(blank=True, choices=[('All', 'All Departments (Full Access)'), ('Scania', 'Scania / Dumper Captain'), ('Excavator', 'Excavator Captain'), ('Grader', 'Motor Grader Captain'), ('Compactor', 'Compactor Captain'), ('Other', 'Other Machinery Captain')], default='All', help_text='Restricts user to only their assigned machinery department in Daily Deployment', max_length=50),
        ),
    ]
