# Generated by Django 6.1 on 2026-09-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0044_user_captain_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyvehicleallocation',
            name='in_time',
            field=models.CharField(blank=True, help_text='In Time / Return Time e.g. 06:00 PM', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dailyvehicleallocation',
            name='out_time',
            field=models.CharField(blank=True, help_text='Out Time / Departure Time e.g. 08:00 AM', max_length=30, null=True),
        ),
    ]
