# Generated by Django 6.1 on 2026-09-03 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0046_alter_companypost_id_alter_dailydeployment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_user_activity',
            field=models.BooleanField(default=False, help_text='Designate whether this user can view the User Activity Monitoring section.'),
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('user_role', models.CharField(max_length=50)),
                ('action_type', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('APPROVE', 'Approved'), ('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out')], db_index=True, max_length=20)),
                ('module_name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
