# Generated by Django 6.1 on 2026-09-03 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0047_user_can_view_user_activity_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Blood Group'),
        ),
        migrations.AddField(
            model_name='employee',
            name='cid_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CID / National ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_rate',
            field=models.FloatField(default=0.0, help_text='Standard Hourly Overtime Rate (Nu/₹ per hr)'),
        ),
        migrations.CreateModel(
            name='OvertimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id_snapshot', models.CharField(db_index=True, help_text='Employee Registration / ID Number', max_length=50)),
                ('employee_name', models.CharField(help_text='Employee Full Name', max_length=150)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('cid_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='CID / National ID')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account Number')),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('overtime_rate', models.FloatField(default=0.0, help_text='Standard Hourly Rate')),
                ('date', models.DateField(db_index=True)),
                ('shift', models.CharField(choices=[('Day', 'Morning / Day Shift'), ('Night', 'Night Shift'), ('General', 'General Shift')], db_index=True, default='Day', max_length=20)),
                ('location_zone', models.CharField(choices=[('Zone 1 & 2', 'Zone 1 & 2'), ('Crushing Plant', 'Crushing Plant'), ('Batching Plant', 'Batching Plant'), ('Borrow Area', 'Borrow Area'), ('Dam Site', 'Dam Site'), ('Power House', 'Power House'), ('Workshop / Garage', 'Workshop / Garage'), ('Road Maintenance', 'Road Maintenance'), ('Other Location', 'Other Location')], db_index=True, default='Zone 1 & 2', max_length=100)),
                ('punch_type', models.CharField(choices=[('IN', 'Punch IN (Shift Start)'), ('OUT', 'Punch OUT (Shift End)'), ('FULL', 'Direct Completed Entry')], default='IN', max_length=20)),
                ('in_time', models.CharField(blank=True, help_text='Punch IN Time e.g. 08:00 AM', max_length=30, null=True)),
                ('out_time', models.CharField(blank=True, help_text='Punch OUT Time e.g. 05:00 PM', max_length=30, null=True)),
                ('overtime_hours', models.FloatField(default=0.0, help_text='Total OT Hours computed')),
                ('overtime_amount', models.FloatField(default=0.0, help_text='Total OT Pay (Hours * Rate)')),
                ('work_description', models.TextField(blank=True, help_text='Task / Machine / Activity Assigned', null=True)),
                ('vehicle_regn', models.CharField(blank=True, help_text='Machine / Vehicle attached', max_length=100, null=True)),
                ('time_keeper_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtimes_approved', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_records', to='portal.employee')),
                ('time_keeper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtimes_logged', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
