# Generated by Django 6.1 on 2026-09-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0048_employee_account_number_employee_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='overtime_rate',
            field=models.FloatField(default=0.0, help_text='Standard Hourly Overtime Rate (Nu/Nu.  per hr)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='system_role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('PROJECT_MANAGER', 'Project Manager (PM)'), ('TIME_KEEPER', 'Time Keeper (QR & Field Scanner)'), ('DEO', 'DEO (Data Entry Operator)'), ('PENDING', 'Pending Approval')], default='PENDING', max_length=20),
        ),
    ]
