# Generated by Django 6.1 on 2026-09-05 02:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0049_alter_employee_overtime_rate_alter_user_system_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(choices=[('General', 'General Shift (8:00 AM - 5:00 PM)'), ('Shift A (Morning)', 'Shift A - Morning (6:00 AM - 2:00 PM)'), ('Shift B (Evening)', 'Shift B - Evening (2:00 PM - 10:00 PM)'), ('Shift C (Night)', 'Shift C - Night (10:00 PM - 6:00 AM)')], default='General', max_length=50)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('On Leave', 'On Leave'), ('Half Day', 'Half Day'), ('Holiday', 'Holiday / Off')], default='Present', max_length=20)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('punch_source', models.CharField(choices=[('QR_SCAN', 'QR / Barcode Scan'), ('MANUAL', 'Manual Entry / Sheet'), ('BULK', 'Bulk Shift Attendance')], default='MANUAL', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='portal.employee')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'employee__name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_date_attendance')],
            },
        ),
    ]
