# Generated by Django 6.1 on 2026-09-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0050_employeeattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedocument',
            name='category',
            field=models.CharField(blank=True, default='Pool Vehicle', max_length=100, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='company_supplier',
            field=models.CharField(blank=True, default='RVJV', max_length=100, null=True, verbose_name='Company / Supplier'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='night_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Night Contact No.'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='night_driver',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Night Driver / Operator'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks / Notes'),
        ),
        migrations.AddField(
            model_name='insurancedocument',
            name='work_site',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Work Site / Location'),
        ),
        migrations.AlterField(
            model_name='insurancedocument',
            name='contact_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Day Contact No.'),
        ),
        migrations.AlterField(
            model_name='insurancedocument',
            name='driver_operator',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Day Driver / Operator'),
        ),
        migrations.AlterField(
            model_name='insurancedocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance Expiry Date'),
        ),
        migrations.AlterField(
            model_name='insurancedocument',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Insurance Provider'),
        ),
        migrations.AlterField(
            model_name='insurancedocument',
            name='issued_on',
            field=models.DateField(blank=True, null=True, verbose_name='Issued On'),
        ),
        migrations.AlterField(
            model_name='insurancedocument',
            name='policy_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Policy No.'),
        ),
        migrations.AlterField(
            model_name='insurancedocument',
            name='registration_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration No.'),
        ),
        migrations.AlterField(
            model_name='insurancedocument',
            name='reports_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reports To'),
        ),
        migrations.AlterField(
            model_name='insurancedocument',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vehicle / Equipment Type'),
        ),
    ]
