# Generated by Django 6.1 on 2026-09-07 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0051_insurancedocument_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User Account', 'verbose_name_plural': '🔐 Manage Logins & User Access Controls'},
        ),
        migrations.AlterModelOptions(
            name='useractivitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Activity Log', 'verbose_name_plural': '⚡ Live User Activity Logs & Audit Stream'},
        ),
    ]
