# Generated by Django 6.1 on 2026-09-07 04:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0052_alter_user_options_alter_useractivitylog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessGuestCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=150)),
                ('contractor_company', models.CharField(blank=True, max_length=150, null=True)),
                ('meal_type', models.CharField(default='LUNCH', max_length=20)),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('is_redeemed', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mess Guest Coupon',
                'verbose_name_plural': '🎟️ Mess Guest Coupons',
            },
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('breakfast_menu', models.TextField(blank=True, null=True)),
                ('lunch_menu', models.TextField(blank=True, null=True)),
                ('dinner_menu', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mess Menu',
                'verbose_name_plural': '📋 Mess Menus',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', '🌅 Breakfast (Nashta)'), ('LUNCH', '☀️ Lunch (Dopahar ka Khana)'), ('SNACKS', '☕ Evening Tea & Snacks'), ('DINNER', '🌙 Dinner (Raat ka Khana)')], db_index=True, default='LUNCH', max_length=20)),
                ('punch_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', '🟢 Success / Served'), ('DUPLICATE', '🔴 Duplicate Punch Blocked'), ('INVALID', '⚠️ Invalid Scan')], default='SUCCESS', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_logs', to='portal.employee')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mess Meal Log',
                'verbose_name_plural': '🍱 Mess Meal Logs',
                'ordering': ['-punch_time'],
            },
        ),
    ]
