# Generated by Django 6.1 on 2026-09-07 05:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0053_messguestcoupon_messmenu_messlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyvehicleallocation',
            name='entry_mode',
            field=models.CharField(default='SCANNER', max_length=30),
        ),
        migrations.AddField(
            model_name='dailyvehicleallocation',
            name='verification_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='entry_mode',
            field=models.CharField(default='SCANNER', max_length=30),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='verification_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='messlog',
            name='entry_mode',
            field=models.CharField(default='SCANNER', max_length=30),
        ),
        migrations.AddField(
            model_name='messlog',
            name='verification_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='MessFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', '🌅 Breakfast'), ('LUNCH', '☀️ Lunch'), ('DINNER', '🌙 Dinner')], default='LUNCH', max_length=20)),
                ('feedback_tag', models.CharField(choices=[('DELICIOUS', '😋 Delicious / Bahut Acha'), ('GOOD', '👍 Good / Sahi Hai'), ('LESS_SALT', '🧂 Needs Less Salt'), ('MORE_SALT', '🧂 Needs More Salt'), ('HARD_ROTI', '🍞 Roti Hard / Cold'), ('CLEANLINESS', '🧹 Cleanliness Issue')], default='GOOD', max_length=30)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_feedbacks', to='portal.employee')),
            ],
            options={
                'verbose_name': 'Mess Feedback',
                'verbose_name_plural': '💬 Mess Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessFoodStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', '🌅 Breakfast (6 AM - 8 AM)'), ('LUNCH', '☀️ Lunch (1 PM - 2 PM)'), ('DINNER', '🌙 Dinner (8 PM - 9 PM)')], max_length=20, unique=True)),
                ('status', models.CharField(choices=[('CLOSED', '🔴 Kitchen Closed'), ('PREPARING', '⏳ Preparing Food'), ('READY_IN_5', '⏰ Ready in 5 Minutes!'), ('READY', '🟢 Food is READY! Please come')], default='CLOSED', max_length=20)),
                ('announcement', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mess Food Status',
                'verbose_name_plural': '📢 Mess Food Statuses',
            },
        ),
    ]
