# Generated by Django 6.1 on 2026-09-07 05:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0054_dailyvehicleallocation_entry_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Mess A (Main Canteen), Mess B (Site 2)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='e.g. MESS_A, MESS_B', max_length=50, unique=True)),
                ('capacity', models.IntegerField(default=200)),
                ('contractor_agency', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mess Location',
                'verbose_name_plural': '🏢 Mess Locations',
            },
        ),
        migrations.AddField(
            model_name='dailyvehicleallocation',
            name='mess_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.messlocation'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='mess_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.messlocation'),
        ),
        migrations.AddField(
            model_name='messlog',
            name='mess_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.messlocation'),
        ),
        migrations.CreateModel(
            name='MessWastageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('meal_type', models.CharField(default='LUNCH', max_length=20)),
                ('prepared_qty_kg', models.FloatField(default=0.0, help_text='Total food prepared in Kg')),
                ('wasted_qty_kg', models.FloatField(default=0.0, help_text='Total food wasted / leftover in Kg')),
                ('contractor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mess_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wastage_logs', to='portal.messlocation')),
            ],
            options={
                'verbose_name': 'Mess Wastage Log',
                'verbose_name_plural': '🗑️ Mess Food Wastage Logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
