# Generated by Django 6.1 on 2026-09-07 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0055_messlocation_dailyvehicleallocation_mess_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_mess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='portal.messlocation'),
        ),
    ]
