# Generated by Django 6.1 on 2026-09-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0056_employee_assigned_mess'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessMealWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Day Shift Lunch, Night Refreshment', max_length=100)),
                ('shift', models.CharField(choices=[('DAY', '☀️ Day / Morning Shift'), ('NIGHT', '🌙 Night Shift'), ('ALL', '⭐ All Shifts')], default='DAY', max_length=20)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', '🌅 Breakfast'), ('LUNCH', '☀️ Lunch'), ('SNACKS', '☕ Evening Tea & Snacks'), ('DINNER', '🌙 Dinner'), ('NIGHT_REFRESHMENT', '☕ Night Refreshment / Midnight Meal')], default='LUNCH', max_length=30)),
                ('start_time', models.TimeField(help_text='e.g. 06:00:00')),
                ('end_time', models.TimeField(help_text='e.g. 08:00:00')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Mess Meal Window Schedule',
                'verbose_name_plural': '⏰ Mess Meal Window Schedules',
                'ordering': ['shift', 'display_order', 'start_time'],
            },
        ),
    ]
