# Generated by Django 6.1 on 2026-09-08 05:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0057_messmealwindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='camp_room',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Camp Room / Block'),
        ),
        migrations.AddField(
            model_name='employee',
            name='camp_status',
            field=models.CharField(choices=[('INSIDE', '🟢 Inside Camp'), ('OUTSIDE', '🔴 Outside / On Duty'), ('ON_LEAVE', '🏖️ On Leave')], default='INSIDE', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Exit / Resignation Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='exit_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for Leaving'),
        ),
        migrations.CreateModel(
            name='CampMovementLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', '🟢 Entry / In'), ('OUT', '🔴 Exit / Out')], db_index=True, default='IN', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('gate_name', models.CharField(default='Main Camp Gate', max_length=100)),
                ('entry_mode', models.CharField(default='GUARD_SCAN', max_length=30)),
                ('purpose', models.CharField(choices=[('SHIFT_DUTY', '🚜 Shift / Site Duty'), ('PERSONAL', '🛍️ Personal / Market'), ('MEDICAL', '🏥 Medical / Clinic'), ('LEAVE', '🏖️ Home Leave / Travel'), ('OTHER', '📌 Other Reason')], default='SHIFT_DUTY', max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_logs', to='portal.employee')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camp Gate Movement Log',
                'verbose_name_plural': '🚪 Camp Gate Movement Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
