# Generated by Django 6.1 on 2026-09-08 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0058_employee_camp_room_employee_camp_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(default='Main Site Camp Residence', max_length=150)),
                ('latitude', models.FloatField(default=0.0, help_text='Camp center latitude coordinate')),
                ('longitude', models.FloatField(default=0.0, help_text='Camp center longitude coordinate')),
                ('geofence_radius_meters', models.IntegerField(default=350, help_text='Allowed punch distance radius in meters')),
                ('geofence_enabled', models.BooleanField(default=False, help_text='Enforce GPS location check during self punch')),
                ('curfew_start_time', models.TimeField(default=datetime.time(21, 30), help_text='Night curfew threshold e.g. 9:30 PM')),
                ('curfew_max_outside_hours', models.IntegerField(default=4, help_text='Max hours allowed outside camp before alert')),
                ('voice_guidance_enabled', models.BooleanField(default=True, help_text='Speak Hindi voice confirmation on punch')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camp System Setting',
                'verbose_name_plural': '⚙️ Camp System Settings',
            },
        ),
    ]
