# Generated by Django 6.1 on 2026-09-08 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0059_campsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Linked Employee profile in workforce roster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='portal.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
