# Generated by Django 6.1 on 2026-09-09 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0060_user_employee_alter_employee_entered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_social_feed_mode',
            field=models.BooleanField(default=False, help_text='Renders dashboard as an interactive social media feed (likes, comments, shares) instead of KPI summary cards.', verbose_name='Enable Instagram/FB Social Feed Dashboard Mode'),
        ),
        migrations.AlterField(
            model_name='campsetting',
            name='voice_guidance_enabled',
            field=models.BooleanField(default=False, help_text='Audio voice greeting setting'),
        ),
        migrations.CreateModel(
            name='FeedEntryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_comments', to='portal.campmovementlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feed_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedEntryLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_likes', to='portal.campmovementlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feed_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('log_entry', 'user')},
            },
        ),
    ]
