# Generated by Django 6.1 on 2026-09-09 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0061_user_enable_social_feed_mode_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedentrylike',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feedentrycomment',
            name='entry_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='feedentrylike',
            name='entry_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedentrycomment',
            name='log_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_comments', to='portal.campmovementlog'),
        ),
        migrations.AlterField(
            model_name='feedentrylike',
            name='log_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_likes', to='portal.campmovementlog'),
        ),
    ]
