# Generated by Django 6.1 on 2026-09-11 04:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0062_alter_feedentrylike_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_code', models.CharField(help_text='e.g. Block A, Block B ... Block P', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('NATIONAL', '🇧🇹 National / Bhutanese'), ('EXPATRIATE', '🇮🇳 Expatriate / Indian'), ('MIXED', '🌐 Mixed')], default='MIXED', max_length=50)),
                ('total_rooms', models.IntegerField(default=10)),
                ('capacity', models.IntegerField(default=60)),
                ('caretaker_name', models.CharField(blank=True, max_length=100, null=True)),
                ('caretaker_contact', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Camp Block',
                'verbose_name_plural': '🏢 Camp Blocks (A-P)',
            },
        ),
        migrations.CreateModel(
            name='CampRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='e.g. P1, P2, O17, A3', max_length=50, unique=True)),
                ('capacity', models.IntegerField(default=4)),
                ('room_key_number', models.CharField(blank=True, help_text='e.g. KEY-P1', max_length=50, null=True)),
                ('key_status', models.CharField(choices=[('ISSUED', '🔑 Key Issued to Resident'), ('IN_GATE_BOX', '🔏 Key in Gate Box'), ('LOST', '⚠️ Key Lost / Missing')], default='ISSUED', max_length=30)),
                ('fan_count', models.IntegerField(default=1, help_text='Number of ceiling/wall fans in room')),
                ('fan_status', models.CharField(choices=[('WORKING', '✅ Working'), ('FAULTY', '⚠️ Faulty / Repair Needed'), ('NONE', '❌ None')], default='WORKING', max_length=30)),
                ('tubelight_count', models.IntegerField(default=2, help_text='Number of tubelights/bulbs in room')),
                ('tubelight_status', models.CharField(choices=[('WORKING', '✅ Working'), ('FAULTY', '⚠️ Faulty / Repair Needed'), ('NONE', '❌ None')], default='WORKING', max_length=30)),
                ('door_lock_status', models.CharField(choices=[('OK', '✅ Door Lock OK'), ('REPAIR_NEEDED', '⚠️ Lock Damaged / Loose')], default='OK', max_length=30)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='portal.campblock')),
                ('key_issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_room_keys', to='portal.employee')),
            ],
            options={
                'verbose_name': 'Camp Room',
                'verbose_name_plural': '🚪 Camp Rooms & Fixtures',
            },
        ),
        migrations.CreateModel(
            name='CampAssetAllotment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(blank=True, help_text='e.g. Bed 1, Bed 2', max_length=30, null=True)),
                ('bed_cot_allotted', models.BooleanField(default=True)),
                ('mattress_allotted', models.BooleanField(default=True)),
                ('mattress_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pillow_allotted', models.BooleanField(default=True)),
                ('blanket_allotted', models.BooleanField(default=True)),
                ('bucket_mug_issued', models.BooleanField(default=True)),
                ('locker_key_issued', models.BooleanField(default=False)),
                ('locker_number', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(choices=[('GOOD', '✅ Good Condition'), ('DAMAGED', '⚠️ Damaged'), ('RETURNED', '📦 Returned')], default='GOOD', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allotted_camp_assets', to='portal.employee')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_assets', to='portal.camproom')),
            ],
            options={
                'verbose_name': 'Person Inventory Allotment',
                'verbose_name_plural': '🛋️ Person Asset Allotments (Bed, Mattress, Pillow)',
            },
        ),
        migrations.CreateModel(
            name='MessScanLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', '🌅 Breakfast'), ('LUNCH', '☀️ Lunch'), ('DINNER', '🌙 Dinner')], default='LUNCH', max_length=20)),
                ('scan_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(default='ALLOWED', max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_scan_logs', to='portal.employee')),
                ('mess_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='portal.messlocation')),
            ],
            options={
                'verbose_name': 'Mess Meal Scan Log',
                'verbose_name_plural': '🍱 Mess Meal Scan Logs',
                'ordering': ['-scan_timestamp'],
            },
        ),
    ]
