# Generated by Django 6.1 on 2026-09-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0063_campblock_camproom_campassetallotment_messscanlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='campassetallotment',
            name='fan_allotted',
            field=models.BooleanField(default=True),
        ),
    ]
