# Generated by Django 6.1 on 2026-09-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0064_campassetallotment_fan_allotted'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledocument',
            name='chassis_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='company',
            field=models.CharField(blank=True, default='RVJV', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='engine_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
