# Generated by Django 6.1 on 2026-09-12 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0065_vehicledocument_chassis_no_vehicledocument_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('leave_type', models.CharField(choices=[('LABOUR_BATCH', '👷 Labour Multi-MSW'), ('COMPANY_STAFF', '🏢 Company Staff')], default='LABOUR_BATCH', max_length=30)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('total_days', models.IntegerField(default=1)),
                ('leave_category', models.CharField(blank=True, default='Home Leave', max_length=50, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('replacement_worker', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('ACTIVE_ON_LEAVE', '🟡 Active On Leave'), ('RETURNED', '✅ Returned / Rejoined'), ('CANCELLED', '❌ Cancelled'), ('EXTENDED', '⏳ Extended')], db_index=True, default='ACTIVE_ON_LEAVE', max_length=30)),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='Manager Sir / HR', max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='portal.employee')),
            ],
            options={
                'verbose_name': 'Employee Leave Record',
                'verbose_name_plural': '📋 Employee Leave Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessAssetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('category', models.CharField(choices=[('KITCHEN_EQUIPMENT', '🍳 Kitchen & Cooking Equipment'), ('DINING_UTENSILS', '🍽️ Dining & Utensils'), ('CLEANING_HOUSEKEEPING', '🧹 Cleaning & Housekeeping'), ('STAFF_UNIFORM_PPE', '🦺 Staff Uniforms & PPE'), ('LPG_GAS', '🔥 LPG Gas Cylinders'), ('GENERAL_APPLIANCE', '🔌 Electrical & General Appliances')], default='DINING_UTENSILS', max_length=50)),
                ('asset_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('total_quantity', models.IntegerField(default=1)),
                ('available_quantity', models.IntegerField(default=1)),
                ('unit', models.CharField(default='Pcs', max_length=30)),
                ('condition_status', models.CharField(choices=[('GOOD', '✅ Good Condition'), ('FAIR', '🟡 Fair / Usable'), ('REPAIR_NEEDED', '⚠️ Repair Needed'), ('CONDEMNED', '❌ Damaged / Condemned')], default='GOOD', max_length=30)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mess_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='portal.messlocation')),
            ],
            options={
                'verbose_name': 'Mess Asset Item',
                'verbose_name_plural': '🍳 Mess Asset Items (Inventory)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MessAssetAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_to_type', models.CharField(choices=[('STAFF_MEMBER', '👤 Staff / Worker'), ('MESS_LOCATION', '🏢 Mess Location / Section')], default='STAFF_MEMBER', max_length=30)),
                ('staff_role', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ISSUED', '📤 Issued / In-Use'), ('PARTIALLY_RETURNED', '🔄 Partially Returned'), ('RETURNED', '✅ Returned'), ('LOST_DAMAGED', '⚠️ Lost / Damaged')], db_index=True, default='ISSUED', max_length=30)),
                ('condition_on_issue', models.CharField(default='Good Condition', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mess_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_asset_allocations', to='portal.messlocation')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mess_asset_allocations', to='portal.employee')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='portal.messassetitem')),
            ],
            options={
                'verbose_name': 'Mess Asset Allocation',
                'verbose_name_plural': '📤 Mess Asset Allocations (Issuances)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessAssetReturnLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('returned_quantity', models.IntegerField(default=1)),
                ('condition', models.CharField(choices=[('GOOD', '✅ Good / Reusable'), ('DAMAGED_REPAIRABLE', '⚠️ Damaged (Repairable)'), ('SCRAPPED', '❌ Broken / Scrapped'), ('LOST', '❓ Lost / Missing')], default='GOOD', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_logs', to='portal.messassetallocation')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mess Asset Return Log',
                'verbose_name_plural': '📥 Mess Asset Return Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
