# Generated by Django 6.1 on 2026-09-13 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0066_employeeleaverecord_messassetitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messassetallocation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_asset_allocations', to='portal.camproom'),
        ),
        migrations.AddField(
            model_name='messassetallocation',
            name='room_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dailyvehicleallocation',
            name='category',
            field=models.CharField(choices=[('BEDDING_LINEN', '🛏️ Bedding, Mattresses & Linen'), ('ROOM_FIXTURE', '🏢 Room Fixtures & Electrical'), ('KITCHEN_EQUIPMENT', '🍳 Kitchen & Cooking Equipment'), ('DINING_UTENSILS', '🍽️ Dining & Utensils'), ('CLEANING_HOUSEKEEPING', '🧹 Cleaning & Housekeeping'), ('STAFF_UNIFORM_PPE', '🦺 Staff Uniforms & PPE'), ('LPG_GAS', '🔥 LPG Gas Cylinders'), ('GENERAL_APPLIANCE', '⚡ Electrical & General Appliances'), ('OTHER', '📦 General Store & Other Assets')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='messassetallocation',
            name='allocated_to_type',
            field=models.CharField(choices=[('ROOM', '🏢 Room / Barrack'), ('RESIDENT', '👤 Room Resident / Individual Worker'), ('MESS_LOCATION', '🍳 Mess Facility / Section'), ('STAFF_MEMBER', '👨\u200d🍳 Mess Staff (Cook / Cleaner / Helper)')], db_index=True, default='RESIDENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='messassetallocation',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'In-Use / Issued'), ('PARTIALLY_RETURNED', 'Partially Returned'), ('RETURNED', 'Returned'), ('LOST_DAMAGED', 'Lost / Damaged')], db_index=True, default='ISSUED', max_length=30),
        ),
    ]
