# Generated by Django 6.1 on 2026-09-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0067_messassetallocation_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messassetallocation',
            name='location_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='messassetallocation',
            name='staff_name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
