# Generated by Django 6.1 on 2026-09-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0068_messassetallocation_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messassetallocation',
            name='gate_pass_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messassetallocation',
            name='handover_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='messassetallocation',
            name='handover_to',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='messassetallocation',
            name='vehicle_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='messassetallocation',
            name='allocated_to_type',
            field=models.CharField(choices=[('ROOM', '🏢 Room / Barrack'), ('RESIDENT', '👤 Room Resident / Individual Worker'), ('MESS_LOCATION', '🍳 Mess Facility / Section'), ('STAFF_MEMBER', '👨\u200d🍳 Mess Staff (Cook / Cleaner / Helper)'), ('OTHER_SITE', '🚚 Other Site / External Transfer')], db_index=True, default='RESIDENT', max_length=30),
        ),
    ]
