# Generated by Django 6.1 on 2026-09-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0069_messassetallocation_gate_pass_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messlog',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('SNACKS', 'Evening Tea & Snacks'), ('DINNER', 'Dinner')], db_index=True, default='LUNCH', max_length=20),
        ),
    ]
