# Generated by Django 6.1 on 2026-09-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0070_alter_messlog_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campblock',
            name='capacity',
            field=models.IntegerField(default=160),
        ),
        migrations.AlterField(
            model_name='campblock',
            name='total_rooms',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='camproom',
            name='capacity',
            field=models.IntegerField(default=8),
        ),
    ]
