# Generated by Django 6.1 on 2026-09-15 02:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0071_alter_campblock_capacity_alter_campblock_total_rooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyStoreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(help_text='e.g. SAF-HLM-001', max_length=50, unique=True, verbose_name='Item Code / SKU')),
                ('name', models.CharField(max_length=150, verbose_name='Equipment Name')),
                ('category', models.CharField(choices=[('HELMET', 'Safety Helmet / Hard Hat'), ('SHOES', 'Safety Shoes / Steel-Toe Boots'), ('VEST', 'High-Visibility Safety Vest'), ('GLOVES', 'Protective Hand Gloves'), ('HARNESS', 'Full Body Safety Harness / Lanyard'), ('GOGGLES', 'Eye Protection Goggles / Visor'), ('EARPLUG', 'Ear Plugs / Hearing Protection'), ('RESPIRATOR', 'Dust Mask / Chemical Respirator'), ('OTHER', 'Other Safety Equipment')], default='OTHER', max_length=50)),
                ('unit', models.CharField(default='Pairs', help_text='e.g. Pairs, Pcs, Sets', max_length=30)),
                ('specification', models.CharField(blank=True, help_text='Brand, Model, Size range, standard certifications', max_length=255, null=True)),
                ('total_stock', models.IntegerField(default=0, verbose_name='Total Stock Purchased')),
                ('available_stock', models.IntegerField(default=0, verbose_name='Current Stock Available')),
                ('minimum_alert_level', models.IntegerField(default=5, verbose_name='Minimum Threshold Alert')),
                ('warranty_months', models.IntegerField(default=6, help_text='Standard replacement cycle in months', verbose_name='Warranty Period (Months)')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Standard penalty if damaged/lost before warranty expiry', max_digits=10, verbose_name='Fine Amount (Nu / Rs)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Safety Store Item',
                'verbose_name_plural': '🦺 Safety Store Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SafetyEquipmentIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('size_specification', models.CharField(blank=True, help_text='Size/Spec allocated, e.g. 8, 9, L, XL', max_length=50, null=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active (In Use)'), ('REPLACED_NORMAL', 'Replaced (Normal Expired)'), ('REPLACED_PREMATURE', 'Replaced (Premature Damage/Loss)'), ('RETURNED_RESIGNED', 'Returned (Employee Resigned)'), ('VOID', 'Cancelled / Void')], default='ACTIVE', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_equipment_issues', to='portal.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_issues_given', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_records', to='portal.safetystoreitem')),
            ],
            options={
                'verbose_name': 'Safety Equipment Issue',
                'verbose_name_plural': '👷 Safety Equipment Issues',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyReplacementAndFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('WORN_OUT_NORMAL', 'Normal Wear & Tear (Warranty Expired)'), ('DAMAGED_PREMATURE', 'Premature Damage / Torn Before Warranty'), ('LOST_BY_WORKER', 'Lost / Misplaced by Employee'), ('SIZE_EXCHANGE', 'Size Exchange (Good / Unused Condition)'), ('OTHER', 'Other Reason')], default='DAMAGED_PREMATURE', max_length=30)),
                ('old_item_condition', models.CharField(blank=True, help_text='e.g. Sole separated, strap torn, lost', max_length=150, null=True)),
                ('is_premature', models.BooleanField(default=False)),
                ('days_used', models.IntegerField(default=0)),
                ('warranty_days', models.IntegerField(default=0)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fine_status', models.CharField(choices=[('NO_FINE', 'No Fine (Normal / Exempted)'), ('PENDING_APPROVAL', 'Pending Manager Approval'), ('APPROVED_SALARY_DEDUCTION', 'Approved for Salary Deduction'), ('PAID_CASH', 'Paid in Cash / Resolved'), ('WAIVED', 'Waived / Excused by Manager')], default='PENDING_APPROVAL', max_length=30)),
                ('waived_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_replacements_and_fines', to='portal.employee')),
                ('new_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_from_record', to='portal.safetyequipmentissue')),
                ('original_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacements_made', to='portal.safetyequipmentissue')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_replacements_handled', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replacement_incidents', to='portal.safetystoreitem')),
            ],
            options={
                'verbose_name': 'Safety Replacement & Fine',
                'verbose_name_plural': '⚖️ Safety Replacements & Fines',
                'ordering': ['-replacement_date', '-created_at'],
            },
        ),
    ]
