# Generated by Django 6.1 on 2026-09-15 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0072_safetystoreitem_safetyequipmentissue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyreplacementandfine',
            name='full_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total item cost used in formula (Cost / Life * Remaining Months)', max_digits=10),
        ),
        migrations.AddField(
            model_name='safetyreplacementandfine',
            name='months_used',
            field=models.IntegerField(default=0, help_text='Total months completed before replacement'),
        ),
        migrations.AddField(
            model_name='safetyreplacementandfine',
            name='remaining_months',
            field=models.IntegerField(default=0, help_text='Warranty months remaining when replaced'),
        ),
        migrations.AddField(
            model_name='safetystoreitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_items_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='safetystoreitem',
            name='category',
            field=models.CharField(default='General PPE', help_text='Category name, e.g. Head Protection, Shoes, Reflectors, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='safetystoreitem',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Standard full cost used for prorated fine calculation (Cost / Life * Remaining Months)', max_digits=10, verbose_name='Full Cost / Replacement Value (Nu)'),
        ),
    ]
