# Generated by Django 6.1 on 2026-09-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0073_safetyreplacementandfine_full_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiredOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('hire_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('cid_no', models.CharField(blank=True, max_length=50, null=True)),
                ('hire_type', models.CharField(choices=[('Driver/Operator', 'Driver / Operator'), ('Mechanic/Supervisor', 'Mechanic / Supervisor'), ('Other', 'Other')], default='Driver/Operator', max_length=50)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(choices=[('Bhutanese', 'Bhutanese'), ('Indian', 'Indian'), ('Other', 'Other')], default='Bhutanese', max_length=50)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hired Operator',
                'verbose_name_plural': '🔧 Hired Vehicles & Operators',
                'ordering': ['hire_agent', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabourRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(choices=[('Bhutanese', 'Bhutanese'), ('Indian', 'Indian'), ('Other', 'Other')], default='Indian', max_length=50)),
                ('cid_number', models.CharField(blank=True, max_length=50, null=True)),
                ('voter_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Leave', 'On Leave'), ('Left', 'Left'), ('Registered', 'Registered'), ('Transferred', 'Transferred')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Labour Record',
                'verbose_name_plural': '👷 Labour Register',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RVJVEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(choices=[('Bhutanese', 'Bhutanese'), ('Indian', 'Indian'), ('Other', 'Other')], default='Bhutanese', max_length=50)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('work_permit', models.CharField(blank=True, max_length=100, null=True)),
                ('cid_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Left', 'Left')], default='Active', max_length=20)),
                ('relieving_date', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RVJV Employee',
                'verbose_name_plural': '🏢 RVJV Employee Register',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContractorWorkerPPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('contractor_name', models.CharField(db_index=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('reflector', models.CharField(blank=True, max_length=500, null=True)),
                ('safety_boot', models.CharField(blank=True, max_length=500, null=True)),
                ('helmet', models.CharField(blank=True, max_length=500, null=True)),
                ('gloves', models.CharField(blank=True, max_length=500, null=True)),
                ('face_mask', models.CharField(blank=True, max_length=500, null=True)),
                ('safety_goggles', models.CharField(blank=True, max_length=500, null=True)),
                ('ear_plug', models.CharField(blank=True, max_length=500, null=True)),
                ('shoulder_pads', models.CharField(blank=True, max_length=500, null=True)),
                ('body_harness', models.CharField(blank=True, max_length=500, null=True)),
                ('raincoat', models.CharField(blank=True, max_length=500, null=True)),
                ('extra_ppe_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contractor Worker PPE',
                'verbose_name_plural': '🦺 Contractor Worker PPE Issuances',
                'ordering': ['contractor_name', 'name'],
                'unique_together': {('worker_id', 'contractor_name')},
            },
        ),
    ]
