# Generated by Django 6.1 on 2026-09-18 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0074_manpower_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeFormRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('fw_leave', 'Foreign Worker Leave Form (2026)'), ('rvjv_leave', 'RVJV Employee Leave Form'), ('no_dues', 'No Due Certificate (Clearance)'), ('material_req', 'Material Requisition Form'), ('stationery_req', 'Stationery Requisition Form'), ('pantry_req', 'Pantry Requisition Form'), ('hr_req', 'Human Resource Requisition Form'), ('temp_emp_info', 'Temporary Employee Information Form')], db_index=True, max_length=50)),
                ('form_title', models.CharField(max_length=200)),
                ('serial_no', models.CharField(db_index=True, max_length=60, unique=True)),
                ('created_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_printed_at', models.DateTimeField(blank=True, null=True)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / In Progress'), ('SUBMITTED', 'Submitted / Active'), ('PRINTED', 'Printed / Issued'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_office_forms', to=settings.AUTH_USER_MODEL)),
                ('last_printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_office_forms', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_office_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Office Form Record',
                'verbose_name_plural': '📑 Office Form Records & Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
