from django.urls import path
from . import views

app_name = 'fleet'

urlpatterns = [
    path("global/", views.fleet_dashboard, name="global_dashboard"),
    path("lubrication/", views.lubrication_view, name="lubrication"),
    path("api/lubrication/add/", views.api_add_lubrication, name="api_add_lubrication"),
    path("api/lubrication/import/", views.api_import_lubrication, name="api_import_lubrication"),
    path("api/lubrication/sample/", views.download_lubrication_sample, name="lubrication_sample"),
    path("api/lubrication/export/", views.api_export_lubrication, name="api_export_lubrication"),
    path("api/lubrication/export-pdf/", views.api_export_lubrication_pdf, name="api_export_lubrication_pdf"),
    path("api/lubrication/delete/<int:log_id>/", views.api_delete_lubrication, name="api_delete_lubrication"),
    path("api/lubrication/edit/<int:log_id>/", views.api_edit_lubrication, name="api_edit_lubrication"),
    path("api/lubrication/poll/", views.api_lubrication_poll, name="api_lubrication_poll"),
    path("tyre/", views.tyre_view, name="tyre"),
    path("api/tyre/add/", views.api_add_tyre, name="api_add_tyre"),
    path("api/tyre/import/", views.api_import_tyre, name="api_import_tyre"),
    path("api/tyre/sample/", views.download_tyre_sample, name="tyre_sample"),
    path("api/tyre/export/", views.api_export_tyre, name="api_export_tyre"),
    path("api/tyre/export-pdf/", views.api_export_tyre_pdf, name="api_export_tyre_pdf"),
    path("api/tyre/delete/<int:log_id>/", views.api_delete_tyre, name="api_delete_tyre"),
    path("api/tyre/edit/<int:log_id>/", views.api_edit_tyre, name="api_edit_tyre"),
    path("api/tyre/poll/", views.api_tyre_poll, name="api_tyre_poll"),
    path("api/tyre/live/", views.api_live_tyre, name="api_live_tyre"),
    path("api/vehicle-report/", views.api_vehicle_report, name="api_vehicle_report"),
    path("api/vehicle-report-pdf/", views.api_vehicle_report_pdf, name="api_vehicle_report_pdf"),
    path("vehicle/add/", views.api_add_vehicle, name="api_add_vehicle"),
    path("vehicle/edit/<int:vehicle_id>/", views.api_edit_vehicle, name="api_edit_vehicle"),
    path("vehicle/delete/<int:vehicle_id>/", views.api_delete_vehicle, name="api_delete_vehicle"),
    path("movements/", views.vehicle_movements, name="vehicle_movements"),
    path("movements/directory/", views.movement_directory, name="movement_directory"),
    path("movements/directory/export/", views.directory_export, name="directory_export"),
    path("movements/add/", views.add_vehicle_movement, name="add_vehicle_movement"),
    path("movements/add-vehicle/", views.add_fleet_vehicle, name="add_fleet_vehicle"),
    path("movements/<int:movement_id>/edit/", views.edit_vehicle_movement, name="edit_vehicle_movement"),
    path("movements/<int:movement_id>/delete/", views.delete_vehicle_movement, name="delete_vehicle_movement"),
    path("movements/api/live/", views.movements_live_api, name="movements_live_api"),
    path("movements/export/", views.movements_export, name="movements_export"),
    
    path("spare-parts/", views.spare_parts_view, name="spare_parts"),
    path("api/spare-parts/add/", views.api_add_spare_part_transaction, name="api_add_spare_part_transaction"),
    path("api/spare-parts/export/", views.export_spare_parts, name="export_spare_parts"),
    path("api/spare-parts/export-pdf/", views.export_spare_parts_pdf, name="export_spare_parts_pdf"),
    path("api/spare-parts/delete/<int:tx_id>/", views.api_delete_spare_part_transaction, name="api_delete_spare_part_transaction"),
    path("api/spare-parts/approve/<int:tx_id>/", views.api_approve_spare_part_transaction, name="api_approve_spare_part_transaction"),
    path("api/spare-parts/edit/<int:tx_id>/", views.api_edit_spare_part_transaction, name="api_edit_spare_part_transaction"),
    path("api/spare-parts/suppliers/", views.api_spare_parts_suppliers, name="api_spare_parts_suppliers"),
    path("api/spare-parts/search/", views.api_spare_parts_search, name="api_spare_parts_search"),
    path("api/vehicles/lookup/", views.api_vehicles_lookup, name="api_vehicles_lookup"),
    path("vehicles/export-excel/", views.export_vehicles_excel, name="export_vehicles_excel"),
    path("vehicles/export-pdf/", views.export_vehicles_pdf, name="export_vehicles_pdf"),
    path("profiles/", views.vehicle_profiles_hub, name="vehicle_profiles"),
    path("breakdowns/", views.breakdown_register, name="breakdown_register"),
    path("api/breakdown/add/", views.api_add_breakdown, name="api_add_breakdown"),
    path("api/breakdown/resolve/<int:log_id>/", views.api_resolve_breakdown, name="api_resolve_breakdown"),
    path('<str:section_id>/', views.fleet_dashboard, name="dashboard"),
    path('kundali/<int:vehicle_id>/', views.vehicle_kundali, name='kundali'),
    path('api/lubrication/live/', views.api_live_lubrication, name='api_live_lubrication'),
]
