# Generated by Django 5.2.15 on 2026-08-14 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portal', '0021_section_module_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dno', models.CharField(max_length=100, verbose_name='Door No')),
                ('regn', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration No')),
                ('model_name', models.CharField(blank=True, max_length=150, null=True)),
                ('latest_hmr', models.FloatField(default=0.0)),
                ('hmr_date', models.DateField(blank=True, null=True)),
                ('s_service', models.FloatField(blank=True, null=True)),
                ('m_service', models.FloatField(blank=True, null=True)),
                ('l_service', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.companypost')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_vehicles', to='portal.section')),
            ],
        ),
        migrations.CreateModel(
            name='RepairLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField()),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('complaint', models.TextField(blank=True, null=True)),
                ('parts_used', models.TextField(blank=True, null=True)),
                ('qty', models.CharField(blank=True, max_length=50, null=True)),
                ('mechanic', models.CharField(blank=True, max_length=100, null=True)),
                ('hmr_at_breakdown', models.FloatField(blank=True, null=True)),
                ('kmr_at_breakdown', models.FloatField(blank=True, null=True)),
                ('out_date', models.DateField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_logs', to='fleet.fleetvehicle')),
            ],
        ),
    ]
