# Generated by Django 5.2.15 on 2026-08-14 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('portal', '0021_section_module_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleetvehicle',
            name='l_service',
        ),
        migrations.RemoveField(
            model_name='fleetvehicle',
            name='m_service',
        ),
        migrations.RemoveField(
            model_name='fleetvehicle',
            name='s_service',
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='brakes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='electricals',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='engine',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='gearbox',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='steering',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('license_no', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='portal.section')),
            ],
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='fleet.driver'),
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(max_length=100, verbose_name='Service Interval (e.g., 250H)')),
                ('last_date', models.DateField()),
                ('current_hmr', models.FloatField(blank=True, null=True)),
                ('last_hmr', models.FloatField(blank=True, null=True)),
                ('next_due', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='fleet.fleetvehicle')),
            ],
        ),
    ]
