# Generated by Django 5.2.15 on 2026-08-14 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_remove_fleetvehicle_l_service_and_more'),
        ('portal', '0021_section_module_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_models', to='portal.section')),
            ],
        ),
    ]
