# Generated by Django 5.2.15 on 2026-08-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehiclemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fleetvehicle',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='repairlog',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='servicelog',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
