# Generated by Django 6.1 on 2026-08-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_driver_extra_data_fleetvehicle_extra_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='section',
        ),
        migrations.RemoveField(
            model_name='fleetvehicle',
            name='section',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='section',
        ),
    ]
