# Generated by Django 6.1 on 2026-08-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_remove_driver_section_remove_fleetvehicle_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LubricationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('work_order_no', models.CharField(blank=True, max_length=150, null=True)),
                ('oil_type', models.CharField(max_length=150)),
                ('qty', models.FloatField()),
                ('unit', models.CharField(default='L', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('manpower_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('entered_on', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lubrication_logs', to='fleet.fleetvehicle')),
            ],
        ),
    ]
