# Generated by Django 6.1 on 2026-08-26 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_vehiclemovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemovement',
            name='vehicle_number',
            field=models.CharField(default='', help_text='Vehicle number (typed)', max_length=150),
        ),
        migrations.AlterField(
            model_name='vehiclemovement',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='fleet.fleetvehicle'),
        ),
    ]
