# Generated by Django 6.1 on 2026-08-26 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_vehiclemovement_vehicle_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TyreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('work_order_no', models.CharField(blank=True, max_length=150, null=True)),
                ('punctures', models.PositiveIntegerField(default=0)),
                ('big_patches', models.PositiveIntegerField(default=0)),
                ('small_patches', models.PositiveIntegerField(default=0)),
                ('nozzles', models.PositiveIntegerField(default=0)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('big_patches_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('small_patches_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('opening_fitting_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('entered_on', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre_entered', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_logs', to='fleet.fleetvehicle')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
    ]
