# Generated by Django 6.1 on 2026-08-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_tyrelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiredVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regn', models.CharField(max_length=100, unique=True, verbose_name='Registration / Equipment No')),
                ('equipment_type', models.CharField(blank=True, max_length=200, null=True)),
                ('hire_by', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Owner / Vendor')),
                ('agreement_ref', models.CharField(blank=True, max_length=150, null=True, verbose_name='Hire Agreement Reference (WO)')),
                ('contract_status', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('regn',),
            },
        ),
        migrations.AddField(
            model_name='lubricationlog',
            name='vendor',
            field=models.CharField(blank=True, help_text='Vendor / Owner name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tyrelog',
            name='vendor',
            field=models.CharField(blank=True, help_text='Vendor / Owner name', max_length=200, null=True),
        ),
    ]
