# Generated by Django 6.1 on 2026-08-29 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_hiredvehicle_lubricationlog_vendor_tyrelog_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='SKU or Part Number', max_length=150, unique=True)),
                ('part_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, help_text='Engine, Electrical, Suspension, etc.', max_length=150, null=True)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('current_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=5)),
                ('location', models.CharField(blank=True, help_text='Store Location or Bin Number', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('part_name',),
            },
        ),
        migrations.CreateModel(
            name='SparePartTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=10)),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per unit', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('reference_no', models.CharField(blank=True, help_text='PO No, Invoice No, or WO No', max_length=150, null=True)),
                ('mechanic', models.CharField(blank=True, help_text='Who received the part', max_length=150, null=True)),
                ('supplier', models.CharField(blank=True, help_text='Applicable for Stock In', max_length=200, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='fleet.sparepart')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Applicable for Stock Out', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts_used', to='fleet.fleetvehicle')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
    ]
