# Generated by Django 6.1 on 2026-08-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_sparepart_spareparttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparttransaction',
            name='location',
            field=models.CharField(blank=True, help_text='Location for Stock Out', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='spareparttransaction',
            name='manpower_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Manpower cost', max_digits=12),
        ),
        migrations.AddField(
            model_name='spareparttransaction',
            name='wo_no',
            field=models.CharField(blank=True, help_text='Work Order No', max_length=150, null=True),
        ),
    ]
