# Generated by Django 6.1 on 2026-08-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_spareparttransaction_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='valuation_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Latest valuation rate', max_digits=12),
        ),
    ]
