# Generated by Django 6.1 on 2026-08-29 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_sparepart_valuation_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spareparttransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_spare_parts_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spareparttransaction',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
