# Generated by Django 6.1 on 2026-08-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0015_spareparttransaction_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyrelog',
            name='valve_pin_number',
            field=models.CharField(blank=True, help_text='Valve Pin Number', max_length=150, null=True),
        ),
    ]
