# Generated by Django 6.1 on 2026-09-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_add_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyrelog',
            name='company',
            field=models.CharField(blank=True, help_text='Company / Brand (e.g. MRF, Apollo)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tyrelog',
            name='driver_name',
            field=models.CharField(blank=True, help_text='Driver name', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tyrelog',
            name='entry_type',
            field=models.CharField(choices=[('PUNCTURE', 'Puncture / Repair'), ('ISSUE', 'New Tyre Issued')], default='PUNCTURE', max_length=20),
        ),
        migrations.AddField(
            model_name='tyrelog',
            name='ply_number',
            field=models.CharField(blank=True, help_text='Ply number / rating (e.g. 16PR)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tyrelog',
            name='size_of_tyre',
            field=models.CharField(blank=True, help_text='Size of tyre (e.g. 10.00-20)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tyrelog',
            name='tyre_number',
            field=models.CharField(blank=True, help_text='Tyre Number / Serial No', max_length=150, null=True),
        ),
    ]
