from django.urls import path
from . import views
from . import views_forms

urlpatterns = [
    path('', views.auth_view, name='auth_view'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('post/<str:entry_key>/', views.post_router_view, name='post_router_view'),
    path('teams/', views.teams_view, name='teams'),
    path('teams/<int:user_id>/edit/', views.edit_employee_role_view, name='edit_employee_role'),
    path('api/teams/mess-worker/save/', views.api_save_mess_worker_details, name='api_save_mess_worker_details'),
    path('api/teams/mess-worker/meal-status/<int:user_id>/', views.api_get_mess_worker_meal_status, name='api_get_mess_worker_meal_status'),
    path('api/teams/mess-worker/meal-approval/', views.api_manage_mess_meal_approval, name='api_manage_mess_meal_approval'),
    path('api/teams/user/switch-category/', views.api_switch_user_category, name='api_switch_user_category'),
    path('vehicles/', views.vehicles_view, name='vehicles'),
    path('search/', views.global_search_view, name='global_search'),
    path('api/search-suggestions/', views.search_suggestions_api, name='search_suggestions_api'),
    path('employee/<int:user_id>/profile/', views.employee_profile_view, name='employee_profile'),
    path('worker/<int:emp_id>/profile/', views.worker_profile_view, name='worker_profile'),
    path('send-email/', views.send_email_view, name='send_email'),
    path('system-settings/', views.system_settings_view, name='system_settings'),
    path('my-profile/', views.my_profile_view, name='my_profile'),
    path('change-password/', views.change_password_view, name='change_password'),
    path('logout/', views.logout_view, name='logout'),
    path('api/manager/vehicle/<int:vehicle_id>/history/', views.manager_vehicle_history_api, name='manager_vehicle_history_api'),
    path('documents/alerts/', views.document_alerts, name='document_alerts'),
    path('api/request-otp/', views.request_otp, name='request_otp'),
    path('api/verify-otp/', views.verify_otp, name='verify_otp'),
    path('add_employee/', views.add_employee_view, name='add_employee'),
    path('api/export-portal/', views.export_portal_data, name='export_portal_data'),
    path('api/employees/export/', views.export_employees_custom, name='export_employees_custom'),
    path('api/employees/export-excel/', views.export_employees_get, name='export_employees_excel'),
    path('api/employees/export-pdf/', views.export_employees_pdf, name='export_employees_pdf'),
    path('employee/<int:emp_id>/edit_action/', views.edit_employee_action, name='edit_employee_action'),
    path('employee/<int:emp_id>/delete_action/', views.delete_employee_action, name='delete_employee_action'),
    path('rc/<int:doc_id>/edit/', views.edit_rc_action, name='edit_rc_action'),
    path('rc/<int:doc_id>/delete/', views.delete_rc_action, name='delete_rc_action'),
    path('insurance/<int:doc_id>/edit/', views.edit_insurance_action, name='edit_insurance_action'),
    path('insurance/<int:doc_id>/delete/', views.delete_insurance_action, name='delete_insurance_action'),
    path('asset-permit/<str:source_type>/<int:doc_id>/delete/', views.delete_asset_permit_action, name='delete_asset_permit_action'),
    path('asset-permit/<str:source_type>/<int:doc_id>/edit/', views.edit_asset_permit_action, name='edit_asset_permit_action'),
    path('documents/insurance/export/', views.insurance_export_hub_view, name='insurance_export_hub'),
    path('documents/insurance/export-excel/', views.export_insurance_excel, name='export_insurance_excel'),
    path('documents/insurance/export-pdf/', views.export_insurance_pdf, name='export_insurance_pdf'),
    path('documents/insurance/import-excel/', views.import_insurance_excel_action, name='import_insurance_excel'),
    path('api/notifications/unread/', views.get_unread_notifications, name='get_unread_notifications'),
    path('api/notifications/mark-read/', views.mark_notifications_read, name='mark_notifications_read'),
    path('api/notifications/delete-all/', views.delete_all_notifications, name='delete_all_notifications'),
    path('api/profile/update-notification-prefs/', views.update_notification_prefs, name='update_notification_prefs'),
    path('notifications/', views.notifications_page, name='notifications'),
    path('document/edit/<str:doc_type>/<int:doc_id>/', views.document_edit_view, name='document_edit'),
    path('notification/<int:notif_id>/', views.notification_detail_view, name='notification_detail'),
    path('api/import-documents/', views.import_documents_view, name='import_documents'),
    path('api/ocr-extract/', views.ocr_extract_view, name='ocr_extract'),
    path('deployment/', views.deployment_view, name='deployment'),
    path('deployment/add/', views.add_deployment_action, name='add_deployment'),
    path('deployment/edit/<int:dep_id>/', views.edit_deployment_action, name='edit_deployment'),
    path('deployment/delete/<int:dep_id>/', views.delete_deployment_action, name='delete_deployment'),
    path('deployment/delete-by-date/', views.delete_deployment_by_date_action, name='delete_deployment_by_date'),
    path('api/deployment/import/', views.import_deployment_excel, name='import_deployment'),
    path('api/deployment/sample/', views.download_deployment_template, name='deployment_sample'),
    path('shifts/', views.shifts_view, name='shifts'),
    path('shifts/update/', views.update_shift_action, name='update_shift'),
    path('api/employees/import/', views.import_employees_excel, name='import_employees'),
    path('api/employees/template/', views.download_employee_template, name='download_employee_template'),
    path('api/shifts/template/', views.download_shift_template, name='download_shift_template'),
    path('api/shifts/import/', views.import_shifts_excel, name='import_shifts'),
    path('api/shifts/export/', views.export_shifts_report, name='export_shifts'),
    path('api/shifts/bulk-update/', views.bulk_update_shift_api, name='bulk_update_shift'),
    path('api/live/dashboard/', views.api_live_dashboard, name='api_live_dashboard'),
    path('api/live/deployment/', views.api_live_deployments, name='api_live_deployments'),
    path('api/live/shifts/', views.api_live_shifts, name='api_live_shifts'),
    path('api/global/poll/', views.api_global_poll, name='api_global_poll'),
    path('deployment/export-excel/', views.export_deployment_excel, name='export_deployment_excel'),
    path('deployment/allocation/add/', views.api_add_vehicle_allocation, name='add_vehicle_allocation'),
    path('deployment/allocation/edit/<int:alloc_id>/', views.api_edit_vehicle_allocation, name='edit_vehicle_allocation'),
    path('deployment/allocation/get/<int:alloc_id>/', views.api_get_vehicle_allocation, name='get_vehicle_allocation'),
    path('deployment/allocation/delete/<int:alloc_id>/', views.api_delete_vehicle_allocation, name='delete_vehicle_allocation'),
    path('api/deployment/vehicle-lookup/', views.api_deployment_vehicle_lookup, name='api_deployment_vehicle_lookup'),
    path('deployment/vehicle-lookup/', views.api_deployment_vehicle_lookup, name='deployment_vehicle_lookup_alias'),
    path('deployment/export-allocation-excel/', views.export_allocation_excel, name='export_allocation_excel'),
    path('deployment/export-allocation-pdf/', views.export_allocation_pdf, name='export_allocation_pdf'),
    path('deployment/export/', views.deployment_export_hub_view, name='deployment_export_page'),
    
    # Live Chat urls
    path('chat/', views.chat_room, name='chat_room'),
    path('api/chat/send/', views.api_send_message, name='api_send_message'),
    path('api/chat/messages/<int:user_id>/', views.api_get_messages, name='api_get_messages'),
    path('api/chat/send-audio/', views.api_send_audio, name='api_send_audio'),
    path('api/chat/unread/', views.api_unread_chats, name='api_unread_chats'),
    path('api/chat/heartbeat/', views.api_chat_heartbeat, name='api_chat_heartbeat'),
    path('api/chat/presence/', views.api_chat_presence, name='api_chat_presence'),
    path('user-activity/', views.user_activity_view, name='user_activity'),
    path('user-activity/export/', views.export_user_activity, name='export_user_activity'),
    path('user-activity/export-pdf/', views.export_user_activity_pdf, name='export_user_activity_pdf'),
    path('api/live/user-activity/', views.api_live_user_activity, name='api_live_user_activity'),
    path('api/admin/users/update-access/', views.api_admin_update_user_access, name='api_admin_update_user_access'),
    path('api/admin/users/create/', views.api_admin_create_user, name='api_admin_create_user'),
    
    # Overtime & Time Keeper Management URLs
    path('overtime/scan/', views.overtime_scanner_view, name='overtime_scan'),
    path('overtime/dashboard/', views.overtime_dashboard_view, name='overtime_dashboard'),
    path('overtime/', views.overtime_dashboard_view, name='overtime_hub'),
    path('overtime/export/', views.overtime_export_hub_view, name='overtime_export_page'),
    path('api/overtime/employee-lookup/', views.api_overtime_employee_lookup, name='api_overtime_employee_lookup'),
    path('api/overtime/submit-punch/', views.api_overtime_submit_punch, name='api_overtime_submit_punch'),
    path('api/overtime/get/<int:record_id>/', views.api_overtime_get_record, name='api_overtime_get_record'),
    path('api/overtime/update/<int:record_id>/', views.api_overtime_update_record, name='api_overtime_update_record'),
    path('api/overtime/delete/<int:record_id>/', views.api_overtime_delete_record, name='api_overtime_delete_record'),
    path('api/overtime/approve/<int:record_id>/', views.api_overtime_approve, name='api_overtime_approve'),
    path('api/overtime/bulk-approve/', views.api_overtime_bulk_approve, name='api_overtime_bulk_approve'),
    path('api/overtime/bulk-delete/', views.api_overtime_bulk_delete, name='api_overtime_bulk_delete'),
    path('overtime/export-excel/', views.export_overtime_excel, name='export_overtime_excel'),
    path('overtime/export-csv/', views.export_overtime_csv, name='export_overtime_csv'),
    path('overtime/export-pdf/', views.export_overtime_pdf, name='export_overtime_pdf'),
    path('system/backup/download/', views.download_system_backup, name='download_system_backup'),
    
    # Attendance Management URLs
    path('attendance/', views.attendance_hub_view, name='attendance_hub'),
    path('attendance/scan/', views.attendance_scanner_view, name='attendance_scan'),
    path('attendance/scan/', views.attendance_scanner_view, name='attendance_scanner'),
    path('attendance/muster-roll/', views.attendance_muster_roll_view, name='attendance_muster_roll'),
    path('api/attendance/submit-punch/', views.api_attendance_submit_punch, name='api_attendance_submit_punch'),
    path('api/attendance/mark-single/', views.api_attendance_mark_single, name='api_attendance_mark_single'),
    path('api/attendance/bulk-mark/', views.api_attendance_bulk_mark, name='api_attendance_bulk_mark'),
    path('api/attendance/assign-shift/', views.api_attendance_assign_shift, name='api_attendance_assign_shift'),
    path('attendance/export/daily-excel/', views.export_attendance_daily_excel, name='export_attendance_daily_excel'),
    path('attendance/export/muster-excel/', views.export_attendance_muster_excel, name='export_attendance_muster_excel'),
    path('attendance/export/pdf/', views.export_attendance_pdf, name='export_attendance_pdf'),
    path('api/attendance/export-daily-excel/', views.export_attendance_daily_excel),
    path('api/attendance/export-muster-excel/', views.export_attendance_muster_excel),
    path('api/attendance/export-pdf/', views.export_attendance_pdf),


    # Mess Management System Routes
    path('mess/', views.mess_root_view, name='mess_root_view'),
    path('mess/login/', views.mess_login_view, name='mess_login_view'),
    path('mess/user/', views.mess_user_view, name='mess_user_view'),
    path('mess/kitchen/', views.mess_kitchen_view, name='mess_kitchen_view'),
    path('mess/monitor/', views.mess_monitor_view, name='mess_monitor_view'),
    path('mess/scan/', views.mess_scan_view, name='mess_scan_view'),
    path('api/mess/punch/', views.api_mess_punch, name='api_mess_punch'),
    path('mess/api/self-pass/', views.api_generate_self_pass, name='api_generate_self_pass'),
    path('mess/api/feedback/', views.api_submit_mess_feedback, name='api_submit_mess_feedback'),
    path('mess/api/food-status/', views.api_update_food_status, name='api_update_food_status'),
    path('mess/api/update-menu/', views.api_update_mess_menu, name='api_update_mess_menu'),
    path('mess/api/meal-window/save/', views.api_save_meal_window, name='api_save_meal_window'),
    path('mess/api/meal-window/delete/', views.api_delete_meal_window, name='api_delete_meal_window'),
    path('mess/reports/', views.mess_reports_view, name='mess_reports_view'),
    path('mess/export-excel/', views.export_mess_excel, name='export_mess_excel'),
    path('mess/export-pdf/', views.export_mess_pdf, name='export_mess_pdf'),

    path('mess/contractor/', views.mess_contractor_view, name='mess_contractor_view'),
    path('mess/api/log-wastage/', views.api_log_mess_wastage, name='api_log_mess_wastage'),
    path('mess/api/add-location/', views.api_add_mess_location, name='api_add_mess_location'),
    path('mess/api/delete-location/', views.api_delete_mess_location, name='api_delete_mess_location'),
    path('mess/api/add-timekeeper/', views.api_add_timekeeper, name='api_add_timekeeper'),
    path('mess/api/search-employees/', views.api_search_employees, name='api_search_employees'),
    path('mess/api/assign-mess/', views.api_assign_employee_mess, name='api_assign_employee_mess'),
    path('mess/api/quick-add-worker/', views.api_quick_create_and_assign_worker, name='api_quick_create_and_assign_worker'),
    path('mess/api/mark-resigned/', views.api_mess_mark_worker_resigned, name='api_mess_mark_worker_resigned'),
    path('mess/api/sync-desktop-employees/', views.api_sync_desktop_employees, name='api_sync_desktop_employees'),
    path('mess/qr-poster/<int:mess_id>/', views.mess_qr_poster_view, name='mess_qr_poster_view'),
    path('mess/claim-pass/<int:mess_id>/', views.mess_claim_pass_view, name='mess_claim_pass_view'),

    # Camp Management System Routes (Gate Security & HR Desk)
    path('camp/', views.camp_root_view, name='camp_root_view'),
    path('camp/dashboard/', views.camp_dashboard_view, name='camp_dashboard_view'),
    path('camp/gate/', views.camp_gate_view, name='camp_gate_view'),
    path('camp/api/gate-punch/', views.api_camp_gate_punch, name='api_camp_gate_punch'),
    path('camp/api/lookup-worker/', views.api_camp_lookup_worker, name='api_camp_lookup_worker'),
    path('camp/gate-poster/', views.camp_gate_poster_view, name='camp_gate_poster_view'),
    path('camp/gate-punch/', views.camp_gate_self_punch_view, name='camp_gate_self_punch_view'),
    path('camp/user/', views.camp_user_view, name='camp_user_view'),
    path('camp/hr/', views.camp_hr_view, name='camp_hr_view'),
    path('camp/api/hr/add-employee/', views.api_hr_add_employee, name='api_hr_add_employee'),
    path('camp/api/hr/deactivate-employee/', views.api_hr_deactivate_employee, name='api_hr_deactivate_employee'),
    path('camp/api/hr/mark-leave/', views.api_hr_mark_leave, name='api_hr_mark_leave'),
    path('camp/api/live-stats/', views.api_camp_live_stats, name='api_camp_live_stats'),
    path('camp/api/feed/like/', views.api_feed_toggle_like, name='api_feed_toggle_like'),
    path('camp/api/feed/comment/', views.api_feed_add_comment, name='api_feed_add_comment'),
    path('camp/api/feed/comments/', views.api_feed_get_comments, name='api_feed_get_comments'),
    path('camp/api/settings/', views.api_camp_settings, name='api_camp_settings'),
    path('camp/reports/', views.camp_reports_view, name='camp_reports_view'),
    path('camp/export-excel/', views.export_camp_excel, name='export_camp_excel'),
    path('camp/export/universal/', views.export_camp_universal_excel, name='export_camp_universal_excel'),
    path('camp/export/universal-pdf/', views.export_camp_universal_pdf, name='export_camp_universal_pdf'),
    path('camp/api/export-preview/', views.api_camp_export_preview, name='api_camp_export_preview'),
    path('camp/api/export-data/', views.export_camp_universal_excel, name='api_camp_universal_export'),
    path('camp/export-pdf/', views.export_camp_pdf, name='export_camp_pdf'),
    path('camp/api/movement/<int:log_id>/edit/', views.api_camp_movement_edit, name='api_camp_movement_edit'),
    path('camp/api/movement/<int:log_id>/delete/', views.api_camp_movement_delete, name='api_camp_movement_delete'),
    path('camp/hr/export-excel/', views.export_camp_hr_excel, name='export_camp_hr_excel'),
    path('camp/hr/export-pdf/', views.export_camp_hr_pdf, name='export_camp_hr_pdf'),
    path('camp/api/room-detail/<int:room_id>/', views.api_camp_room_detail, name='api_camp_room_detail'),
    path('api/camp/room-detail/<int:room_id>/', views.api_camp_room_detail, name='api_camp_room_detail_alt'),
    path('camp/api/block-detail/<int:block_id>/', views.api_camp_block_detail, name='api_camp_block_detail'),
    path('camp/api/block-save/', views.api_camp_block_save, name='api_camp_block_save'),
    path('camp/api/block-delete/<int:block_id>/', views.api_camp_block_delete, name='api_camp_block_delete'),
    path('camp/api/room-save/', views.api_camp_room_save, name='api_camp_room_save'),
    path('camp/api/room-delete/<int:room_id>/', views.api_camp_room_delete, name='api_camp_room_delete'),
    path('camp/api/room-assign/', views.api_camp_room_assign_resident, name='api_camp_room_assign_resident'),
    path('camp/api/room-remove/<int:emp_id>/', views.api_camp_room_remove_resident, name='api_camp_room_remove_resident'),
    path('camp/api/resident/change-bed/', views.api_camp_resident_change_bed, name='api_camp_resident_change_bed'),
    path('camp/api/asset-toggle/', views.api_camp_asset_toggle, name='api_camp_asset_toggle'),
    path('camp/api/master-allotments/', views.api_camp_master_allotments, name='api_camp_master_allotments'),
    path('camp/export-master-allotments-excel/', views.export_camp_master_allotments_excel, name='export_camp_master_allotments_excel'),
    path('camp/api/room/update-key/', views.api_camp_room_update_key, name='api_camp_room_update_key'),
    path('camp/api/trade-roster/', views.api_camp_trade_roster, name='api_camp_trade_roster'),
    path('camp/api/worker/mark-leave/', views.api_camp_worker_mark_leave, name='api_camp_worker_mark_leave'),
    path('camp/api/worker/edit/', views.api_camp_worker_edit, name='api_camp_worker_edit'),
    path('camp/api/leave/search-worker/', views.api_leave_search_worker, name='api_leave_search_worker'),

    # Camp Curfew & Overstay Breach Resolution API
    path('camp/api/curfew/resolve/<int:emp_id>/', views.api_camp_curfew_resolve, name='api_camp_curfew_resolve'),

    # Leave Management Lifecycle APIs
    path('camp/api/leave/create/', views.api_leave_create, name='api_leave_create'),
    path('camp/api/leave/return/', views.api_leave_return, name='api_leave_return'),
    path('camp/api/leave/records/', views.api_leave_records, name='api_leave_records'),
    path('camp/api/leave/record/<int:record_id>/edit/', views.api_leave_record_edit, name='api_leave_record_edit'),
    path('camp/api/leave/record/<int:record_id>/delete/', views.api_leave_record_delete, name='api_leave_record_delete'),
    path('camp/api/leave/cancel-active/<int:emp_id>/', views.api_leave_cancel_active, name='api_leave_cancel_active'),

    # Mess & Operational Asset Management APIs
    path('camp/api/mess-assets/', views.api_mess_asset_list, name='api_mess_asset_list'),
    path('camp/api/mess-assets/create/', views.api_mess_asset_create, name='api_mess_asset_create'),
    path('camp/api/mess-assets/add/', views.api_mess_asset_create, name='api_mess_asset_add'),
    path('camp/api/mess-assets/add-item/', views.api_mess_asset_create, name='api_mess_asset_add_item'),
    path('camp/api/mess-assets/<int:asset_id>/edit/', views.api_mess_asset_edit, name='api_mess_asset_edit'),
    path('camp/api/mess-assets/<int:asset_id>/delete/', views.api_mess_asset_delete, name='api_mess_asset_delete'),
    path('camp/api/mess-assets/allocation/<int:alloc_id>/edit/', views.api_mess_allocation_edit, name='api_mess_allocation_edit'),
    path('camp/api/mess-assets/allocation/<int:alloc_id>/delete/', views.api_mess_allocation_delete, name='api_mess_allocation_delete'),
    path('camp/api/mess-assets/return-log/<int:log_id>/delete/', views.api_mess_return_log_delete, name='api_mess_return_log_delete'),
    path('camp/api/mess-assets/issue/', views.api_mess_asset_issue, name='api_mess_asset_issue'),
    path('camp/api/mess-assets/return/', views.api_mess_asset_return, name='api_mess_asset_return'),
    path('camp/api/mess-assets/history/', views.api_mess_asset_history, name='api_mess_asset_history'),
    path('camp/api/room-occupants/', views.api_room_occupants, name='api_room_occupants'),
    path('camp/api/search-workers/', views.api_camp_search_workers, name='api_camp_search_workers'),
    path('camp/api/quick-add-worker/', views.api_camp_quick_add_worker, name='api_camp_quick_add_worker'),
    path('api/reports/native-pdf/', views.api_render_native_pdf, name='api_render_native_pdf'),

    # Mess Meal Logs Edit & Delete APIs
    path('mess/api/log/<int:log_id>/edit/', views.api_mess_log_edit, name='api_mess_log_edit'),
    path('mess/api/log/<int:log_id>/delete/', views.api_mess_log_delete, name='api_mess_log_delete'),

    # Safety Department Management & Enforcement APIs
    path('safety/dashboard/', views.safety_dashboard_view, name='safety_dashboard_view'),
    path('safety/api/item/create/', views.api_safety_item_create, name='api_safety_item_create'),
    path('safety/api/item/<int:item_id>/edit/', views.api_safety_item_edit, name='api_safety_item_edit'),
    path('safety/api/item/<int:item_id>/delete/', views.api_safety_item_delete, name='api_safety_item_delete'),
    path('safety/api/item/<int:item_id>/restock/', views.api_safety_item_restock, name='api_safety_item_restock'),
    path('safety/api/issue/create/', views.api_safety_issue_create, name='api_safety_issue_create'),
    path('safety/api/issue/<int:issue_id>/edit/', views.api_safety_issue_edit, name='api_safety_issue_edit'),
    path('safety/api/issue/<int:issue_id>/delete/', views.api_safety_issue_delete, name='api_safety_issue_delete'),
    path('safety/api/worker/<int:employee_id>/active-issues/', views.api_safety_worker_active_issues, name='api_safety_worker_active_issues'),
    path('safety/api/replacement/process/', views.api_safety_process_replacement, name='api_safety_process_replacement'),
    path('safety/api/fine/<int:fine_id>/update-status/', views.api_safety_fine_update_status, name='api_safety_fine_update_status'),
    path('safety/api/fine/<int:fine_id>/delete/', views.api_safety_fine_delete, name='api_safety_fine_delete'),
    path('safety/export/fines-excel/', views.export_safety_fines_excel, name='export_safety_fines_excel'),
    path('safety/export/inventory-excel/', views.export_safety_inventory_excel, name='export_safety_inventory_excel'),
    path('safety/export/issues-excel/', views.export_safety_issues_excel, name='export_safety_issues_excel'),
    path('safety/export/report-pdf/', views.export_safety_report_pdf, name='export_safety_report_pdf'),
    path('safety/api/inventory/sync-google-sheet/', views.api_safety_sync_google_sheet_inventory, name='api_safety_sync_google_sheet_inventory'),
    path('safety/api/upload-excel/', views.api_safety_excel_upload, name='api_safety_excel_upload'),
    path('safety/api/employees/search/', views.api_safety_employee_search, name='api_safety_employee_search'),
    path('manpower/', views.manpower_dashboard_view, name='manpower_dashboard'),
    path('api/manpower/sync/', views.api_sync_manpower_data, name='api_sync_manpower_data'),

    # Office Forms & Print Hub
    path('forms/', views_forms.office_forms_hub_view, name='office_forms_hub'),
    path('forms/editor/<str:form_type>/', views_forms.office_form_editor_view, name='office_form_editor'),
    path('forms/editor/<str:form_type>/<int:record_id>/', views_forms.office_form_editor_view, name='office_form_editor_edit'),
    path('forms/print/<int:record_id>/', views_forms.office_form_print_view, name='office_form_print'),
    path('forms/download-template/<str:filename>/', views_forms.download_original_template, name='office_form_download_template'),
    path('api/forms/save/', views_forms.api_save_office_form, name='api_save_office_form'),
    path('api/forms/log-print/<int:record_id>/', views_forms.api_log_office_form_print, name='api_log_office_form_print'),
]

